[env]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
framework = ch32v003fun

[env:003]
board = ch32v003f4p6_evt_r0

; [env:203]
; board = genericCH32V203K8T6
; board_build.clock_source = hse+pll
; board_build.f_cpu = 144000000L

; Uncomment this to use the WCH-link E dongle, which supports printf
; upload_protocol = wlink
; upload_command = wlink flash $SOURCE --enable-sdi-print

; uncomment this to use USB bootloader upload via WCHISP
; upload_protocol = isp
lib_deps = https://github.com/olikraus/u8g2
extra_scripts = pre:fix_u8g2.py
