[env]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
framework = noneos-sdk
monitor_speed = 921600

[env:203]
board = genericCH32V203G6U6
board_build.clock_source = hsi+pll
board_build.f_cpu = 144000000L
lib_deps = https://github.com/michael-betz/font_lib
; lib_deps = symlink://../font_lib


; Uncomment this to use the WCH-link E dongle, which supports printf
; upload_command = wlink flash $SOURCE --enable-sdi-print

; uncomment this to use USB bootloader upload via WCHISP
upload_protocol = isp

; Set SDI_PRINT and DEBUG to 1 for printf through the debug cable (WCH-link E)
; Note that controller will hang on boot if the cable is not connected.
build_flags =
	-D SSD1306_128X32 -D FB_WIDTH=128 -D FB_HEIGHT=32 -D FB_BPP=1
	; -D SDI_PRINT=1 -D DEBUG=1  ; for debug
	-D SDI_PRINT=0 -D DEBUG=0  ; for release

