[platformio]
default_envs = release

[env]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git#f1ae11c
framework = noneos-sdk

board = genericCH32V203G6U6
board_build.clock_source = hsi+pll
board_build.f_cpu = 144000000L
lib_deps =
	https://github.com/hathach/tinyusb.git#0.20.0
	https://github.com/michael-betz/font_lib#0e6857c
	; symlink://../font_lib

[common]
build_flags =
	-Wall
	; OLED driver configuration (for font_lib)
	-D SSD1306_128X32 -D FB_WIDTH=128 -D FB_HEIGHT=32 -D FB_BPP=1
	; add tinyusb to include path
	-I${PROJECT_DIR}/src
	; USB Driver Selection
	-D CFG_TUSB_MCU=OPT_MCU_CH32V20X -D CFG_TUSB_OS=OPT_OS_NONE
	; Hardware revision
	-D PCB_REV="\'-\'"
	; Revision string from git
	!echo '-D GIT_REV=\"'$(git describe --dirty --always --tags)'\"'

[env:debug]
; This enables the SDI printf debug console
; Use it with `pio run -e debug -t upload -t monitor`
; Connect the WCH-link E dongle to the internal J4 header.
; !!! Note that the CH32V will hang on boot if the cable is not connected !!!
upload_command = wlink flash $SOURCE --enable-sdi-print
; Allow to use the non-cached flash as program storage (printf takes > 32 kB!)
; Code in the slow flash runs about 5 times slower.
board_upload.maximum_size = 196608
; Enable SDI printf debug
build_flags = ${common.build_flags} -D SDI_PRINT=1 -D DEBUG=1
build_type = debug

[env:release]
; Use the USB bootloader. Push BOOT0 button while plugging in the USB
upload_protocol = isp
; Disable printf debug, so that everything fits in 32 kB
build_flags = ${common.build_flags} -D SDI_PRINT=0 -D DEBUG=0
build_type = release
